# Generated by Django 3.2.6 on 2021-08-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='名前', null=True)),
                ('address', models.TextField(help_text='住所', null=True)),
                ('latitude', models.FloatField(help_text='緯度', null=True)),
                ('longitude', models.FloatField(help_text='経度', null=True)),
                ('time', models.IntegerField(help_text='所要時間', null=True)),
                ('type', models.TextField(help_text='種類', null=True)),
                ('bad_weather', models.BooleanField(default=False, help_text='悪天候')),
                ('stroller', models.BooleanField(default=False, help_text='ベビーカー')),
                ('nursing_room', models.BooleanField(default=False, help_text='授乳室')),
                ('diaper_stand', models.BooleanField(default=False, help_text='おむつ交換台')),
                ('comment', models.TextField(help_text='コメント', null=True)),
            ],
        ),
    ]
